[metis]
url = "http://127.0.0.1:8080"
# کلید باینری برای راه‌اندازی خود متیس (ربات مستقیماً از آن استفاده نمیکند)
binary_key = "5b945476-f95d-4403-a2b5-156db4ee3212"

[trading]
min_amount_sol = 0.1
max_amount_sol = 0.2
step_sol = 0.00005
min_profit_lamports = 1000
tokens_file = "tokens.txt"

[jito]
url = "https://frankfurt.mainnet.block-engine.jito.wtf"
uuid = "8c7cda54-ef6e-4792-8617-da0341f8d485"
trading_keypair = "/home/ubuntu/arb/wallet/wallet-new.json"
# حداقل تیپ طبق داکیومنت جیتو: 1000 لمپرت
tip_min_lamports = 1000
tip_max_lamports = 1000000
tip_profit_percent = 0.50
# ریت لیمیت ارسال باندل به جیتو: حداکثر 5 در ثانیه
max_bundles_per_second = 5

[rpc]
url = "https://rpc.fra.shyft.to?api_key=farYqEW-7r1vxqok"

[yellowstone_grpc]
# برای راه‌اندازی متیس باینری استفاده میشه
endpoint = "https://grpc.fra.shyft.to"
x_token = "41cd21e6-6a66-493d-bdc6-a7057409c2a1"

[performance]
threads = 4
quote_timeout_ms = 500
